### ISSUE TITLE
Composer: permission denied for nginx user

### ISSUE THREAD

**Issue by tntrex** [spaceonfire/docker-nginx-php-fpm#41]
Running `composer update` for nginx user after command called from root user caused this issue:

```
fopen(/usr/local/composer/cache/repo/http---repo.packagist.org/p-provider-2020-07.json): failed to open stream: Permission denied
```

Maybe setting ACL rule for composer home with default option fix this:

```bash
setfacl -RLdm g:nginx:rwx $COMPOSER_HOME
```

**Comment by hustlahusky** [comment]
Seems error with `hirak/prestissimo` plugin, cant be fixed with default ACL rules.

There is ability to switch to Composer v2, with which this issue not reproduces.
